### ISSUE TITLE
Overkiz not loading

### ISSUE THREAD

**Issue by XalaTheShepard** [iMicknl/ha-tahoma#706]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After installing the v2.11.0 update of Overkiz, the custom component can not be loaded in HA.

### What version of this integration (ha-tahoma) has the issue?

2.11.0

### What version of Home Assistant Core has the issue?

2021.12.9

### Which gateway / hub do you use?

Somfy Tahoma V2 hub

### Device model

All devices

### Home Assistant log

```shell
2022-01-12 12:51:27 ERROR (MainThread) [custom_components.tahoma] __init__() missing 1 required keyword-only argument: 'last_update_time'
```

**Comment by iMicknl** [comment]
Could you try to rollback to previous version? This element hasn't been changed and I wonder why you are facing this.

Did you update your hub?

**Comment by tetienne** [comment]
@iMicknl Perhaps we should update our model to make this argument optional: https://github.com/iMicknl/python-overkiz-api/blob/e20787dcb44b3d56987b8fb652024c2cf60bc99b/pyoverkiz/models.py#L57

@XalaTheShepard Can you please enable the debug log as explained [here](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#enable-debug-logging) and report the new lines you see in the log 🙏

**Comment by XalaTheShepard** [comment]
Dear iMicknl, 

Rolling back to the previous version solved the issue. So only version 2.11.0 is causing this issue. 
My hub is still on the same version as it was with version 2.10.2. 

Dear tetienne, 

I have updated again to version 2.11.0 of the custom component and have updated the debug lines.
Currently HA is rebooting and as soon as the reboot has been completed, I will add the logs.

Many thanks for your support. 

Kind regards, 

Robin

**Comment by XalaTheShepard** [comment]
Dear tetienne, 

Please find below the more detailed logs:
2022-01-12 14:54:53 ERROR (MainThread) [custom_components.tahoma] __init__() missing 1 required keyword-only argument: 'last_update_time'
Traceback (most recent call last):
File "/config/custom_components/tahoma/__init__.py", line 64, in async_setup_entry
setup, scenarios = await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 261, in get_setup
setup = Setup(**humps.decamelize(response))
TypeError: __init__() missing 1 required keyword-only argument: 'last_update_time'

**Comment by iMicknl** [comment]
Are you on Discord? I would love to get your setup definition so we can add that to our automated test suite. It seems yours is different compared to other tahoma setup definitions, thus causing the error. My user is iMick#1903.

We will have a look if we can fix this for the next version, but also for the Overkiz integration that will be added to core in next release.

**Comment by XalaTheShepard** [comment]
Dear iMicknl, 

I have send you a discord invite, so we can have a closer look at this issue. 

Kind regards, 

Robin

**Comment by xekil** [comment]
same problem !

**Comment by xekil** [comment]
```
Logger: homeassistant.setup
Source: components/tahoma/__init__.py:78
First occurred: 10:40:57 (1 occurrences)
Last logged: 10:40:57

Error during setup of component tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tahoma/__init__.py", line 78, in setup
    conf = config[DOMAIN]
KeyError: 'tahoma'
```

**Comment by iMicknl** [comment]
@xekil you don't have the same problem. Your issue is that you still try to setup the integration via the YAML config flow, which is not supported. Please remove the `tahoma` section from your configuration.yaml.

**Comment by xekil** [comment]
I have not given any configuration in the configuration.yaml file, I configure the home assistant graphical interface from the start but a reboot has just solved the problem without any modification ... thank you

**Comment by iMicknl** [comment]
@xekil great, in the future please create a new issue and try some things yourselves first.

**Comment by xekil** [comment]
@iMicknl sorry, sorry, I forgot to specify that I re-download the integration via HACS before restarting

**Comment by hdejongh** [comment]
Hello, 

i still have this issue. I completely removed the integration and re-added it.
Please help.. can't control anything now...

**Comment by tetienne** [comment]
@hdejongh When you up an issue already close because fixed, please add more information. In your case, the error was not exactly the same.

**Comment by hdejongh** [comment]
oh, but i created a bug report but it was closed as duplicated of this one. 
https://github.com/iMicknl/ha-tahoma/issues/714

**Comment by tetienne** [comment]
It was the case. But once fixed, you met an other similar issue.

**Comment by hdejongh** [comment]
ok i'll open a new bug report then!

**Comment by tetienne** [comment]
Nevermind, I already fix it.

**Comment by hdejongh** [comment]
Oh that's fast! Cancelled the bug report.

**Comment by tetienne** [comment]
It was well this one? https://community.home-assistant.io/t/overkiz-api-and-somfy-api/61448/1715

**Comment by hdejongh** [comment]
yes that's the same issue.

**Comment by hdejongh** [comment]
> Nevermind, I already fix it.

Hi Tetienne, do you know if its fixed in 2.12.2?

**Comment by tetienne** [comment]
@hdejongh Yes it is.

**Comment by hdejongh** [comment]
great!! thanks, ill update away!

**Comment by hdejongh** [comment]
@tetienne, just upgraded but still no joy, should i maybe first delete the integration and reinstall it?

**Comment by tetienne** [comment]
You still have the same issue? Can you please copy/paste the logs?

**Comment by hdejongh** [comment]
yes i think so:

HA = core-2022.2.5
OS = Home Assistant OS 7.4
Supervisor = 2022.01.1

`Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:85 
Integration: Overkiz (by Somfy) - Custom component 
First occurred: 10:04:28 AM (1 occurrences) 
Last logged: 10:04:28 AM

__init__() missing 1 required keyword-only argument: 'last_update_time'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 85, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 362, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 61, in __init__
    self.location = Location(**location)
TypeError: __init__() missing 1 required keyword-only argument: 'last_update_time'
`



Home Assistant OS 7.4


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">


Home Assistant OS 7.4


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">



Home Assistant OS 7.4


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">



Home Assistant OS 7.4


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">



Home Assistant OS 7.4


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
